const params=new URLSearchParams(location.search);
const demoMode=location.pathname==='/demo/onboarding'||params.get('demo')==='1';
const token=params.get('token')||'';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const steps=[
  {key:'identity',short:'Identidad',title:'Partamos por lo esencial.',lead:'Cuéntanos cómo se presenta tu negocio y quién será nuestro contacto principal.',minutes:4,fields:[['business_name','Nombre comercial','text','Ej. Casa Aura',true],['legal_name','Razón social','text','Opcional',false],['contact_name','Persona de contacto','text','Nombre y apellido',true],['contact_role','Cargo o función','text','Ej. Dueña',false],['email','Correo','email','nombre@empresa.cl',true],['phone','WhatsApp de contacto','tel','+56 9…',true],['description','¿Qué hace el negocio?','textarea','Descríbelo como se lo explicarías a un nuevo cliente.',true]]},
  {key:'locations',short:'Sedes',title:'¿Dónde y a quién atienden?',lead:'Necesitamos límites claros para no prometer cobertura o atención donde no existe.',minutes:4,fields:[['locations','Sedes, direcciones y referencias','textarea','Una sede por línea. Incluye comuna y referencias aprobadas.',true],['coverage','Comunas o zonas de cobertura','textarea','Indica también las zonas excluidas.',false],['parking','Estacionamiento y acceso','textarea','Si no existe estacionamiento propio, déjalo explícito.',true],['accessibility','Accesibilidad','textarea','Acceso universal, ascensor u otras condiciones confirmadas.',false]]},
  {key:'services',short:'Servicios',title:'¿Qué puede ofrecer el agente?',lead:'Incluye nombres exactos, precios vigentes y cualquier condición que cambie el valor.',minutes:7,fields:[['services','Servicios o productos','textarea','Nombre | precio | duración | descripción. Uno por línea.',true],['price_rules','Variaciones y recargos','textarea','Horarios especiales, tallas, zonas, impuestos o condiciones.',false],['excluded_services','Lo que no ofrecen','textarea','Sirve para que el agente no lo sugiera por parecido.',false]]},
  {key:'capacity',short:'Equipo',title:'Mapeemos la capacidad real.',lead:'Esto permite calcular disponibilidad sin adivinar ni sobreagendar.',minutes:6,fields:[['team','Personas o recursos agendables','textarea','Nombre | función | servicios que realiza | sede.',true],['capacity','Capacidad simultánea','textarea','Cuántas atenciones pueden ocurrir al mismo tiempo y por qué.',true],['schedule','Horarios de atención','textarea','Días, apertura, cierre y descansos por persona o sede.',true],['exceptions','Feriados, vacaciones y bloqueos','textarea','Cómo se informan y quién los mantiene actualizados.',false]]},
  {key:'process',short:'Proceso',title:'Enséñanos cómo se concreta una atención.',lead:'Describe el recorrido ideal desde la primera pregunta hasta el cierre.',minutes:6,fields:[['process','Proceso paso a paso','textarea','Qué pregunta, qué valida, qué datos solicita y cuándo confirma.',true],['required_data','Datos obligatorios del cliente','textarea','Nombre, teléfono, correo, dirección u otros.',true],['payment','Pagos y confirmaciones','textarea','Medios de pago, anticipos, comprobantes y responsables.',false],['aftercare','Qué ocurre después','textarea','Recordatorios, instrucciones previas o seguimiento.',false]]},
  {key:'policies',short:'Políticas',title:'Definamos los límites antes de conversar.',lead:'Las excepciones claras reducen errores y derivaciones innecesarias.',minutes:5,fields:[['cancellations','Cancelación y reagendamiento','textarea','Plazos, costos y excepciones.',true],['refunds','Cambios, devoluciones o garantías','textarea','Si no aplica, indícalo.',false],['restrictions','Restricciones importantes','textarea','Edad, salud, stock, cupos, documentación u otras.',true],['special_cases','Casos especiales','textarea','Qué situaciones requieren confirmación manual.',false]]},
  {key:'faq',short:'Preguntas',title:'¿Qué pregunta la gente una y otra vez?',lead:'Escribe preguntas reales y la respuesta correcta que debería entregar el agente.',minutes:6,fields:[['faq','Preguntas y respuestas frecuentes','textarea','Pregunta: …\nRespuesta aprobada: …',true],['objections','Dudas antes de comprar o reservar','textarea','Precio, confianza, ubicación, tiempos u objeciones frecuentes.',false],['comparisons','Comparaciones permitidas','textarea','Qué puede decir frente a competidores y qué debe evitar.',false]]},
  {key:'forbidden',short:'No afirmar',title:'Ahora, lo que nunca debe inventar.',lead:'Esta sección es crítica. Anota hechos sensibles aunque parezcan obvios.',minutes:4,fields:[['forbidden','Datos que nunca debe afirmar sin respaldo','textarea','Ej. estacionamiento, stock, cobertura, resultados, descuentos.',true],['unknown_behavior','¿Qué debe decir cuando no sabe?','textarea','Escribe la respuesta o criterio de derivación preferido.',true],['sensitive','Temas sensibles o regulados','textarea','Salud, legal, financiero, menores de edad u otros.',false]]},
  {key:'handoff',short:'Derivación',title:'¿Cuándo debe llamar a una persona?',lead:'Diseñemos un traspaso que se sienta natural y no abandone al cliente.',minutes:4,fields:[['handoff_cases','Motivos de derivación','textarea','Reclamos, excepciones, falta de información, pagos, urgencias…',true],['handoff_message','Mensaje de traspaso','textarea','Qué debería decir mientras avisa al equipo.',true],['handoff_owner','Responsables y horario humano','textarea','Quién recibe cada caso y en qué horario.',true],['urgency','Qué se considera urgente','textarea','Describe señales y prioridad.',false]]},
  {key:'voice',short:'Forma de hablar',title:'Hagamos que suene como tu negocio.',lead:'Los ejemplos reales son más útiles que elegir sólo “formal” o “amistoso”.',minutes:5,fields:[['tone','Tono deseado','textarea','Cercano, técnico, elegante, directo… explica con ejemplos.',true],['words_use','Palabras o expresiones que sí usan','textarea','Saludos, cierres y vocabulario propio.',false],['words_avoid','Palabras o expresiones a evitar','textarea','Promesas, diminutivos, modismos o tecnicismos.',false],['examples','Ejemplos de respuestas ideales','textarea','Copia respuestas reales que representen bien al negocio.',true]]},
  {key:'documents',short:'Documentos',title:'Sube las fuentes originales.',lead:'Listas de precios, protocolos, catálogos y documentos nos permiten comprobar cada dato.',minutes:3,upload:true,fields:[['document_notes','Notas sobre los documentos','textarea','Indica cuál está vigente, qué reemplaza o qué falta confirmar.',false],['links','Enlaces útiles','textarea','Sitio web, catálogo, agenda actual o documentos públicos.',false]]},
  {key:'integrations',short:'Sistemas',title:'¿Qué sistemas deben conversar?',lead:'No necesitas saber de tecnología. Cuéntanos qué usas hoy y para qué.',minutes:4,fields:[['systems','Herramientas actuales','textarea','WhatsApp/Zavu, agenda, correo, CRM, planillas, pagos…',true],['owners','Quién administra cada sistema','textarea','Persona y forma de contacto.',false],['notifications','Cómo quieren recibir alertas','textarea','WhatsApp, correo y qué situaciones deben avisarse.',true],['access_notes','Accesos o restricciones','textarea','No escribas contraseñas. Sólo explica quién puede autorizarlos.',false]]},
  {key:'review',short:'Revisión',title:'Revisa antes de enviarnos la información.',lead:'Podrás actualizarla más adelante. Por ahora confirma que refleja correctamente cómo opera el negocio.',minutes:2,review:true,fields:[['approval_notes','Comentario final','textarea','Aclara cualquier información pendiente o decisión todavía abierta.',false]]}
];
let session=null,current=0,responses={},uploadedFiles=[],saveTimer=null;

async function api(url,options={}){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No se pudo completar la operación.');return data}
function inputMarkup(field){const [name,label,type,placeholder,required]=field;const value=responses[steps[current].key]?.[name]||'';const requiredText=required?' <span aria-hidden="true">*</span>':'';if(type==='textarea')return `<div class="field ${steps[current].fields.length%2?'wide':''}"><label for="${name}">${label}${requiredText}</label><textarea id="${name}" name="${name}" placeholder="${esc(placeholder)}" ${required?'required':''}>${esc(value)}</textarea></div>`;return `<div class="field"><label for="${name}">${label}${requiredText}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${required?'required':''}></div>`}
function renderRail(){const list=$('#step-list');list.innerHTML=steps.map((step,index)=>`<li class="${index===current?'active':''} ${index<current?'done':''}" data-number="${index+1}">${esc(step.short)}</li>`).join('')}
function collect(){const form=$('#onboarding-form');const data={};for(const element of form.elements){if(element.name)data[element.name]=element.value.trim()}return data}
function summaryMarkup(){return `<div class="summary-grid">${steps.slice(0,-1).map(step=>{const data=responses[step.key]||{};const filled=Object.values(data).filter(Boolean);return `<article class="summary-card"><span>${esc(step.short)}</span><strong>${filled.length?esc(filled.slice(0,2).join(' · ')).slice(0,340):'Sin información registrada'}</strong></article>`}).join('')}</div>`}
function renderStep(){const step=steps[current];renderRail();$('#step-counter').textContent=`Paso ${current+1} de ${steps.length}`;$('#time-estimate').textContent=`${step.minutes} min aprox.`;$('#progress-bar').style.width=`${((current+1)/steps.length)*100}%`;let extra='';if(step.upload)extra=`<div class="field wide"><div class="file-drop"><strong>PDF, Word, Excel, CSV, TXT o Markdown</strong><p class="lead">Máximo 15 MB por archivo.</p><input id="document-files" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.md"></div><div class="file-list" id="file-list">${uploadedFiles.map(file=>`<div class="file-item"><span>${esc(file.name)}</span><span>${Math.ceil(file.size/1024)} KB</span></div>`).join('')}</div></div>`;if(step.review)extra=summaryMarkup();$('#step-content').innerHTML=`<h1>${esc(step.title)}</h1><p class="lead">${esc(step.lead)}</p>${extra}<div class="field-grid">${step.fields.map(inputMarkup).join('')}</div>`;$('#previous-step').disabled=current===0;$('#next-step').textContent=current===steps.length-1?'Confirmar y enviar':'Guardar y continuar';$('#document-files')?.addEventListener('change',uploadFiles);$('#step-content').querySelectorAll('input,textarea,select').forEach(element=>element.addEventListener('input',scheduleSave));window.scrollTo({top:0,behavior:'smooth'})}
function setSaveState(text,state=''){const node=$('.save-state');node.className=`save-state ${state}`;$('#save-state').textContent=text}
function scheduleSave(){setSaveState('Guardando…','saving');clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveCurrent(false,current),600)}
async function saveCurrent(showError=true,resumeStep=current){if(!session||session.status==='submitted')return;const step=steps[current];const data=collect();responses[step.key]=data;if(demoMode){session.currentStep=resumeStep;sessionStorage.setItem('zeroagent-onboarding-demo',JSON.stringify({responses,current:resumeStep}));setSaveState('Demo guardada en esta pestaña');return}try{await api(`/api/onboarding/${token}/response`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({stepKey:step.key,step:resumeStep,data})});setSaveState('Cambios guardados')}catch(error){setSaveState('No se pudo guardar','error');if(showError)alert(error.message);throw error}}
async function uploadFiles(event){for(const file of event.target.files){setSaveState(`${demoMode?'Leyendo':'Subiendo'} ${file.name}…`,'saving');if(demoMode){uploadedFiles.unshift({id:`demo-${Date.now()}`,name:file.name,size:file.size});setSaveState('Archivo agregado a la demostración');continue}try{const result=await fetch(`/api/onboarding/${token}/files`,{method:'POST',headers:{'content-type':file.type||'application/octet-stream','x-file-name':encodeURIComponent(file.name)},body:file});const data=await result.json();if(!result.ok)throw new Error(data.error);uploadedFiles.unshift(data);setSaveState('Documentos guardados')}catch(error){setSaveState('Falló la carga','error');alert(error.message)}}renderStep()}
async function next(event){event.preventDefault();const form=$('#onboarding-form');if(!form.reportValidity())return;try{await saveCurrent(true,Math.min(12,current+1));if(current<steps.length-1){current++;renderStep();return}if(!demoMode)await api(`/api/onboarding/${token}/submit`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});session.status='submitted';showSuccess()}catch(error){alert(error.message)}}
async function previous(){if(current===0)return;try{await saveCurrent(false)}catch{}current--;renderStep()}
function showSuccess(){$('#onboarding-form').innerHTML=`<section class="success-view"><div class="success-mark">✓</div><h1>Recibimos la información de ${esc(session.business.name)}.</h1><p class="lead">Ahora revisaremos las respuestas y documentos. Si detectamos vacíos o contradicciones, recibirás una segunda ronda breve de preguntas antes de configurar el agente.</p><div class="success-note"><strong>Nada se publica automáticamente.</strong><br>Los datos críticos se validan contigo y el agente pasa por pruebas antes de conectarse a WhatsApp.</div></section>`;$('#onboarding-form').hidden=false;$('#progress-bar').style.width='100%';setSaveState('Entrevista enviada');renderRail()}
async function init(){if(demoMode){const saved=JSON.parse(sessionStorage.getItem('zeroagent-onboarding-demo')||'null');session={status:'open',currentStep:saved?.current||0,business:{name:'Casa Aura · Demo'}};responses=saved?.responses||{identity:{business_name:'Casa Aura',contact_name:'Carolina Silva',contact_role:'Dueña',email:'carolina@casaaura.cl',phone:'+56 9 5555 0182',description:'Centro de bienestar especializado en masajes y tratamientos faciales personalizados.'}};current=Math.min(steps.length-1,session.currentStep);$('#business-name').textContent='Casa Aura · Demo';$('.mini-brand').href='/demo';document.title='Entrevista de ejemplo · Casa Aura';$('#loading').hidden=true;$('#onboarding-form').hidden=false;renderStep();setSaveState('Modo demostración · nada se publica');return}if(!token){$('#loading').hidden=true;$('#error-state').hidden=false;$('#error-message').textContent='El enlace no incluye un código de acceso.';return}try{session=await api(`/api/onboarding/${token}`);responses=session.responses||{};uploadedFiles=session.files||[];current=Math.min(steps.length-1,session.currentStep||0);$('#business-name').textContent=session.business.name;document.title=`Entrevista de ${session.business.name}`;$('#loading').hidden=true;$('#onboarding-form').hidden=false;if(session.status==='submitted'||session.status==='approved')showSuccess();else{renderStep();setSaveState('Progreso guardado')}}catch(error){$('#loading').hidden=true;$('#error-state').hidden=false;$('#error-message').textContent=error.message}}
$('#onboarding-form').addEventListener('submit',next);$('#previous-step').addEventListener('click',previous);init();
