-- Studio (ZeroAgent) — schema inicial en Postgres/Supabase, migrado desde database.sqlite.
-- Ver plan completo: C:\Users\dgonz\.claude\plans\parallel-chasing-bee.md
-- Fase 1: solo tablas + índices + RLS. Las funciones RPC van en una migración aparte
-- (20260819_rpc_functions.sql), escritas releyendo el server.js real sitio por sitio.

create table public.clients (
  id text primary key,
  name text not null,
  niche text not null,
  "desc" text,
  agent_name text,
  agent_tone text,
  agent_avatar_color text,
  agent_role text,
  agent_whatsapp text,
  agent_system_prompt text,
  project_stage text not null default 'intake',
  project_notes text not null default '',
  next_action text not null default '',
  vertical_key text not null default 'custom'
);

create table public.audit_events (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  details_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);

create table public.source_files (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  title text not null,
  source_type text not null,
  original_name text,
  storage_path text,
  mime_type text,
  size_bytes integer not null default 0,
  notes text not null default '',
  content text not null default '',
  status text not null default 'pending_ide',
  version_number integer not null default 1,
  -- deferrable: server.js hoy desactiva PRAGMA foreign_keys durante el restore completo para
  -- poder insertar filas en cualquier orden; acá se logra lo mismo sin desactivar FKs globalmente,
  -- solo difiriendo el chequeo de ESTA constraint hasta el COMMIT de la transacción de restore.
  replaces_source_id text references public.source_files(id) on delete set null deferrable initially deferred,
  created_at timestamptz not null,
  reviewed_at timestamptz
);

create table public.intake_jobs (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  source_id text not null references public.source_files(id) on delete cascade,
  kind text not null,
  status text not null default 'pending_ide',
  instructions text not null,
  created_at timestamptz not null,
  completed_at timestamptz,
  workspace_path text,
  -- SQLite: default '' (string vacío), nunca '{}'. En Postgres el equivalente correcto es NULL,
  -- no un jsonb vacío — el código ya trata "sin proposal" como ausencia, no como objeto vacío.
  proposal_json jsonb,
  error_message text not null default ''
);

create table public.agent_versions (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  version text not null,
  status text not null default 'draft',
  summary text not null default '',
  package_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null,
  approved_at timestamptz,
  unique(client_id, version)
);

create table public.documents (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  title text not null,
  category text not null,
  content text not null
);

create table public.knowledge_items (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  source_id text references public.source_files(id) on delete set null,
  category text not null,
  subject text not null,
  value text not null,
  status text not null default 'approved',
  notes text not null default '',
  confirmed_at timestamptz not null
);

create table public.agent_tests (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  knowledge_item_id text references public.knowledge_items(id) on delete set null,
  question text not null,
  expected_behavior text not null,
  status text not null default 'active',
  -- confirmado muerto en app.js (auditoría independiente) — jsonb por consistencia, sin uso real hoy.
  last_result jsonb,
  created_at timestamptz not null
);

create table public.chats (
  id bigint generated by default as identity primary key,
  client_id text not null references public.clients(id) on delete cascade,
  sender text not null,
  text text not null,
  -- NO es un timestamp real: string de hora local sin fecha (ej. "14:32"), tal cual SQLite.
  "time" text not null
);

create table public.conversation_feedback (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  chat_id bigint not null references public.chats(id) on delete cascade,
  rating text not null,
  correction_text text not null default '',
  source_id text references public.source_files(id) on delete set null,
  created_at timestamptz not null
);

create table public.ai_budget_configs (
  client_id text primary key references public.clients(id) on delete cascade,
  provider text not null default 'openai',
  model text not null default 'gpt-4o-mini',
  cycle_budget_clp real not null default 20000,
  usd_clp real not null default 922,
  alert_50 boolean not null default true,
  alert_75 boolean not null default true,
  alert_90 boolean not null default true,
  cycle_started_at timestamptz not null,
  paused boolean not null default false,
  updated_at timestamptz not null
);

create table public.ai_usage_records (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  occurred_at timestamptz not null,
  provider text not null,
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  estimated_cost_usd real not null default 0,
  conversation_ref text,
  source text not null default 'runtime'
);

create table public.ai_budget_events (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  kind text not null,
  amount_clp real,
  notes text not null default '',
  created_at timestamptz not null
);

create table public.client_infrastructure (
  client_id text primary key references public.clients(id) on delete cascade,
  supabase_url text not null default '',
  project_ref text not null default '',
  credential_alias text not null default '',
  credential_hint text not null default '',
  connection_status text not null default 'not_configured',
  last_checked_at timestamptz,
  updated_at timestamptz not null,
  vercel_project_url text not null default '',
  migration_applied boolean not null default false,
  catalog_seeded boolean not null default false,
  env_vars_set boolean not null default false
);

create table public.agenda_configs (
  client_id text primary key references public.clients(id) on delete cascade,
  config_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null
);

create table public.onboarding_sessions (
  id text primary key,
  client_id text not null references public.clients(id) on delete cascade,
  token text not null unique,
  status text not null default 'sent',
  current_step integer not null default 0,
  expires_at timestamptz not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  submitted_at timestamptz,
  approved_at timestamptz
);
create index onboarding_client_idx on public.onboarding_sessions(client_id, created_at desc);

create table public.onboarding_responses (
  session_id text not null references public.onboarding_sessions(id) on delete cascade,
  step_key text not null,
  data_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null,
  primary key(session_id, step_key)
);

create table public.onboarding_files (
  id text primary key,
  session_id text not null references public.onboarding_sessions(id) on delete cascade,
  original_name text not null,
  storage_path text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes integer not null default 0,
  created_at timestamptz not null
);

create table public.commercial_leads (
  id text primary key,
  name text not null,
  business text not null,
  contact text not null,
  source text not null default 'booking_demo',
  created_at timestamptz not null
);
create index commercial_leads_created_idx on public.commercial_leads(created_at desc);

create table public.prospecting_searches (
  id text primary key,
  vertical text not null,
  location text not null,
  terms text not null,
  coverage text not null default 'comuna',
  status text not null default 'completed',
  result_count integer not null default 0,
  source text not null default 'serper',
  created_at timestamptz not null
);
create index prospecting_searches_created_idx on public.prospecting_searches(created_at desc);

create table public.prospects (
  id text primary key,
  search_id text references public.prospecting_searches(id) on delete set null,
  name text not null,
  vertical text not null default 'agenda',
  category text not null default '',
  location text not null default '',
  address text not null default '',
  website text not null default '',
  domain text not null default '',
  phone text not null default '',
  phone_key text not null default '',
  email text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  facebook text not null default '',
  source text not null default 'manual',
  source_url text not null default '',
  rating real,
  review_count integer not null default 0,
  score integer not null default 0,
  fit text not null default 'low',
  signals_json jsonb not null default '[]'::jsonb,
  suggested_message text not null default '',
  status text not null default 'new',
  notes text not null default '',
  next_action_at timestamptz,
  last_contacted_at timestamptz,
  last_contact_channel text not null default '',
  converted_client_id text references public.clients(id) on delete set null,
  created_at timestamptz not null,
  updated_at timestamptz not null
);
create index prospects_status_idx on public.prospects(status, score desc);
create index prospects_domain_idx on public.prospects(domain);
create index prospects_phone_idx on public.prospects(phone_key);

create table public.prospect_activities (
  id text primary key,
  prospect_id text not null references public.prospects(id) on delete cascade,
  kind text not null,
  summary text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);
create index prospect_activities_idx on public.prospect_activities(prospect_id, created_at desc);

-- Índices sobre columnas FK que no quedaron cubiertas por una PK/UNIQUE/índice compuesto de arriba
-- (SQLite indexa el rowid pero no las FK automáticamente tampoco; esto es puramente para no
-- degradar el rendimiento de los JOINs-en-JS que hace server.js, filtrando siempre por estas columnas).
create index source_files_client_idx on public.source_files(client_id);
create index source_files_replaces_idx on public.source_files(replaces_source_id);
create index intake_jobs_client_idx on public.intake_jobs(client_id);
create index intake_jobs_source_idx on public.intake_jobs(source_id);
create index agent_versions_client_idx on public.agent_versions(client_id);
create index documents_client_idx on public.documents(client_id);
create index knowledge_items_client_idx on public.knowledge_items(client_id);
create index knowledge_items_source_idx on public.knowledge_items(source_id);
create index agent_tests_client_idx on public.agent_tests(client_id);
create index agent_tests_knowledge_item_idx on public.agent_tests(knowledge_item_id);
create index chats_client_idx on public.chats(client_id);
create index conversation_feedback_client_idx on public.conversation_feedback(client_id);
create index conversation_feedback_chat_idx on public.conversation_feedback(chat_id);
create index conversation_feedback_source_idx on public.conversation_feedback(source_id);
create index ai_usage_records_client_idx on public.ai_usage_records(client_id);
create index ai_budget_events_client_idx on public.ai_budget_events(client_id);
create index onboarding_files_session_idx on public.onboarding_files(session_id);
create index prospects_search_idx on public.prospects(search_id);
create index prospects_converted_client_idx on public.prospects(converted_client_id);

-- RLS en todas las tablas, sin políticas para anon/authenticated. Studio solo usa la
-- service_role key (bypassa RLS por diseño de Supabase) — no hay ningún camino público hacia
-- esta base de datos, a diferencia del Supabase de cada cliente (que sí sirve un widget público).
alter table public.clients enable row level security;
alter table public.audit_events enable row level security;
alter table public.source_files enable row level security;
alter table public.intake_jobs enable row level security;
alter table public.agent_versions enable row level security;
alter table public.documents enable row level security;
alter table public.knowledge_items enable row level security;
alter table public.agent_tests enable row level security;
alter table public.chats enable row level security;
alter table public.conversation_feedback enable row level security;
alter table public.ai_budget_configs enable row level security;
alter table public.ai_usage_records enable row level security;
alter table public.ai_budget_events enable row level security;
alter table public.client_infrastructure enable row level security;
alter table public.agenda_configs enable row level security;
alter table public.onboarding_sessions enable row level security;
alter table public.onboarding_responses enable row level security;
alter table public.onboarding_files enable row level security;
alter table public.commercial_leads enable row level security;
alter table public.prospecting_searches enable row level security;
alter table public.prospects enable row level security;
alter table public.prospect_activities enable row level security;
